before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: X7yeraWcP3/n4C1/NhgPettYkmaFlvKwQ/FInYsasRBBclXQHM6hkTetsjHtkR3cNNLDfoofEtw23/F5nQ6OXH7N5iKoKa0OqDXl51/vXnPAVbVlhH1wEqainWp+wXYjYWDZlOC3Op1Ww3XEooEydmSd7ume7RV7L9X1hRdiqAjGasFjaGXxr12s10A20TfzgiUYBBKHgppafsvET0WymSKIChmnC0oCXKuYPnLC8iYI3AxzhhBxlrJhnas9zJchEFcu83CYOz4M3WiwdZvaJ+9+kk3BI6TDlmi04l/kt5t+qP1eF2s7BUuA3j1EVltbn8t6Ue3i0b1yuclZGkEfGkI9KvDsnzBqyrxShYNyClo8SUdjGAJTP5iaJW/ajFPM6XPXqCVwU/tgBVjRBHSwtbWf8nuC19co9OIU3EQq29sUsokuBwxugCTvES/kR7gbHzcIgSNKwB+uETCQ1QFOcvwxKA2RoUR+iOhdwRFj+OxEE3fH2t5DU50zaPMyvBoCVylWeqyJ7fL+P8ebVozQnM0E1TUISG98JtVsBQ/8rclO/L9slBKr6EP9vQRuoK4aeXGBHGSqvN6N4z4i88b0Wsm16ZLu5nqH+O334GPZ2B0AwDwrZkv99vxLlcyrq6qDn9iKxiC/b2zwY9ywrplicKvetWeF3y45a8ClgBKgW6Q= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
